package org.geotools.data.spatialite;

import org.geotools.jdbc.JDBCPrimaryKeyTestSetup;
import org.geotools.jdbc.JDBCTestSetup;

public class SpatiaLitePrimaryKeyTestSetup extends JDBCPrimaryKeyTestSetup {

    protected SpatiaLitePrimaryKeyTestSetup() {
        super(new SpatiaLiteTestSetup());
    }

    @Override
    protected void createAutoGeneratedPrimaryKeyTable() throws Exception {
        run("CREATE TABLE auto( fid INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR)");
        run("SELECT AddGeometryColumn('auto','geom',4326,'POINT',2)");
        run("DROP TRIGGER gsu_auto_geom");
        run("DROP TRIGGER gsi_auto_geom");
        run("DROP TRIGGER gtu_auto_geom");
        run("DROP TRIGGER gti_auto_geom");
        
        run( "INSERT INTO auto VALUES (1, NULL, 'one')");
        run( "INSERT INTO auto VALUES (2, NULL, 'two')");
        run( "INSERT INTO auto VALUES (3, NULL, 'three')");
    }
    
    @Override
    protected void dropAutoGeneratedPrimaryKeyTable() throws Exception {
        run( "DROP TABLE auto");
        run( "DELETE FROM geometry_columns WHERE f_table_name = 'auto'");
    }

    @Override
    protected void createMultiColumnPrimaryKeyTable() throws Exception {
    }

    @Override
    protected void createNonIncrementingPrimaryKeyTable() throws Exception {
    }

    @Override
    protected void createNullPrimaryKeyTable() throws Exception {
    }

    @Override
    protected void createSequencedPrimaryKeyTable() throws Exception {
    }

   

    @Override
    protected void dropMultiColumnPrimaryKeyTable() throws Exception {
    }

    @Override
    protected void dropNonIncrementingPrimaryKeyTable() throws Exception {
    }

    @Override
    protected void dropNullPrimaryKeyTable() throws Exception {
    }

    @Override
    protected void dropSequencedPrimaryKeyTable() throws Exception {
    }

}
