/*
 *    GeoTools - The Open Source Java GIS Toolkit
 *    http://geotools.org
 * 
 *    (C) 2002-2008, Open Source Geospatial Foundation (OSGeo)
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */
package org.geotools.gui.swing.style.sld;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractCellEditor;
import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellEditor;
import org.geotools.gui.swing.icon.IconBundle;
import org.geotools.gui.swing.style.StyleElementEditor;
import org.geotools.map.MapLayer;
import org.geotools.styling.Font;
import org.geotools.styling.StyleBuilder;

/**
 * Font panel
 * 
 * @author Johann Sorel
 */
public class JFontTable extends javax.swing.JPanel implements StyleElementEditor<Font[]> {

    private MapLayer layer = null;
    private static final Icon ICO_UP = IconBundle.getResource().getIcon("16_uparrow");
    private static final Icon ICO_DOWN = IconBundle.getResource().getIcon("16_downarrow");
    private static final Icon ICO_NEW = IconBundle.getResource().getIcon("16_add_data");
    private static final Icon ICO_DELETE = IconBundle.getResource().getIcon("16_delete");
    private final FontModel model = new FontModel(new Font[]{});
    private final FontEditor editor = new FontEditor();

    /** Creates new form JFontsPanel */
    public JFontTable() {
        initComponents();
        init();
    }

    private void init() {
        tabFonts.setTableHeader(null);
        tabFonts.setModel(model);
        tabFonts.getColumnModel().getColumn(0).setCellEditor(editor);
        tabFonts.setDefaultRenderer(Font.class, new FontRenderer());
        tabFonts.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void setLayer(MapLayer layer) {
        editor.setLayer(layer);
        this.layer = layer;
    }

    public MapLayer getLayer() {
        return layer;
    }

    public void setEdited(Font[] fonts) {
        model.setFonts(fonts);
    }

    public Font[] getEdited() {
        return model.getFonts();
    }

    public void apply() {
    }

    public Component getComponent() {
        return this;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabFonts = new javax.swing.JTable();
        guiUp = new javax.swing.JButton();
        guiDown = new javax.swing.JButton();
        guiNew = new javax.swing.JButton();
        guiDelete = new javax.swing.JButton();

        setOpaque(false);

        jScrollPane1.setViewportView(tabFonts);

        guiUp.setIcon(ICO_UP);
        guiUp.setBorderPainted(false);
        guiUp.setContentAreaFilled(false);
        guiUp.setMargin(new java.awt.Insets(2, 2, 2, 2));
        guiUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiUpActionPerformed(evt);
            }
        });

        guiDown.setIcon(ICO_DOWN);
        guiDown.setBorderPainted(false);
        guiDown.setContentAreaFilled(false);
        guiDown.setMargin(new java.awt.Insets(2, 2, 2, 2));
        guiDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiDownActionPerformed(evt);
            }
        });

        guiNew.setIcon(ICO_NEW);
        guiNew.setBorderPainted(false);
        guiNew.setContentAreaFilled(false);
        guiNew.setMargin(new java.awt.Insets(2, 2, 2, 2));
        guiNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiNewActionPerformed(evt);
            }
        });

        guiDelete.setIcon(ICO_DELETE);
        guiDelete.setBorderPainted(false);
        guiDelete.setContentAreaFilled(false);
        guiDelete.setMargin(new java.awt.Insets(2, 2, 2, 2));
        guiDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiDeleteActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(guiNew)
                    .add(guiUp)
                    .add(guiDown)
                    .add(guiDelete)))
        );

        layout.linkSize(new java.awt.Component[] {guiDelete, guiDown, guiNew, guiUp}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(guiUp)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(guiDown)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(guiNew)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(guiDelete)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    private void guiUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiUpActionPerformed
        int index = tabFonts.getSelectionModel().getMinSelectionIndex();

        if (index >= 0) {
            Font f = (Font) model.getValueAt(index, 0);
            model.moveUp(f);
        }
}//GEN-LAST:event_guiUpActionPerformed

    private void guiDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiDownActionPerformed
        int index = tabFonts.getSelectionModel().getMinSelectionIndex();

        if (index >= 0) {
            Font f = (Font) model.getValueAt(index, 0);
            model.moveDown(f);
        }
}//GEN-LAST:event_guiDownActionPerformed

    private void guiNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiNewActionPerformed
        model.newFont();
}//GEN-LAST:event_guiNewActionPerformed

    private void guiDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiDeleteActionPerformed
        int index = tabFonts.getSelectionModel().getMinSelectionIndex();

        if (index >= 0) {
            model.deleteFont(index);
        }
    }//GEN-LAST:event_guiDeleteActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guiDelete;
    private javax.swing.JButton guiDown;
    private javax.swing.JButton guiNew;
    private javax.swing.JButton guiUp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabFonts;
    // End of variables declaration//GEN-END:variables
}

class FontModel extends AbstractTableModel {

    private List<Font> fonts = new ArrayList<Font>();

    FontModel(Font[] fonts) {
        for (Font f : fonts) {
            this.fonts.add(f);
        }
    }

    public void newFont() {
        StyleBuilder sb = new StyleBuilder();
        Font f = sb.createFont("arial", 12);

        fonts.add(f);
        int last = fonts.size() - 1;
        fireTableRowsInserted(last, last);
    }

    public void deleteFont(int index) {
        fonts.remove(index);
        fireTableRowsDeleted(index, index);
    }

    public void moveUp(Font f) {
        int index = fonts.indexOf(f);
        if (index != 0) {
            fonts.remove(f);
            fonts.add(index - 1, f);
            fireTableDataChanged();
        }
    }

    public void moveDown(Font f) {
        int index = fonts.indexOf(f);
        if (index != fonts.size() - 1) {
            fonts.remove(f);
            fonts.add(index + 1, f);
            fireTableDataChanged();
        }
    }

    public void setFonts(Font[] fonts) {
        this.fonts.clear();

        if (fonts != null) {
            for (Font f : fonts) {
                this.fonts.add(f);
            }
        }
        fireTableDataChanged();
    }

    public Font[] getFonts() {
        return fonts.toArray(new Font[fonts.size()]);
    }

    public int getRowCount() {
        return fonts.size();
    }

    public int getColumnCount() {
        return 1;
    }

    @Override
    public boolean isCellEditable(int rowIndex, int columnIndex) {
        return true;
    }

    @Override
    public Class<?> getColumnClass(int columnIndex) {
        return Font.class;
    }

    public Object getValueAt(int rowIndex, int columnIndex) {
        return fonts.get(rowIndex);
    }
}

class FontRenderer extends DefaultTableCellRenderer {

    private String text = "SsIiGg84";

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

        JLabel lbl = (JLabel) super.getTableCellRendererComponent(table, text, isSelected, hasFocus, row, column);

        Font f = (Font) value;
        java.awt.Font font = new java.awt.Font(f.getFontFamily().toString(), java.awt.Font.PLAIN, 12);
        lbl.setFont(font);
        return lbl;
    }
}

class FontEditor extends AbstractCellEditor implements TableCellEditor {//implements TableCellEditor{
    private MapLayer layer = null;
    private JFontPane editpane = new JFontPane();
    private JButton but = new JButton("SsIiGg84");
    private Font font = null;

    public FontEditor() {
        super();
        but.setBorderPainted(false);

        but.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                if (font != null) {
                    JDialog dia = new JDialog();

                    //panneau d'edition           
                    editpane.setEdited(font);

                    dia.setContentPane(editpane);
                    dia.setLocationRelativeTo(but);
                    dia.pack();
                    dia.setModal(true);
                    dia.setVisible(true);

                    font = editpane.getEdited();
                }
            }
        });
    }

    public void setLayer(MapLayer layer) {
        this.layer = layer;
    }

    public MapLayer getLayer() {
        return layer;
    }

    public Object getCellEditorValue() {
        return font;
    }

//    public boolean isCellEditable(EventObject e) {
//        return true;
//    }
    public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {

        if (value != null && value instanceof Font) {
            font = (Font) value;
            java.awt.Font f = new java.awt.Font(font.getFontFamily().toString(), java.awt.Font.PLAIN, 12);
            but.setFont(f);
        } else {
            but.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 12));
            font = null;
        }
        return but;
    }

//    public boolean shouldSelectCell(EventObject anEvent) {
//        return true;
//    }
//
//    public boolean stopCellEditing() {
//        return true;
//    }
//
//    public void cancelCellEditing() {
//    }
//
//    public void addCellEditorListener(CellEditorListener l) {        
//    }
//    
//    public void removeCellEditorListener(CellEditorListener l) {
//    }
}
