/*
 *    GeoTools - The Open Source Java GIS Toolkit
 *    http://geotools.org
 * 
 *    (C) 2002-2008, Open Source Geospatial Foundation (OSGeo)
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */
package org.geotools.gui.swing.style.sld;

import java.awt.Component;
import org.geotools.gui.swing.style.StyleElementEditor;
import org.geotools.map.MapLayer;
import org.geotools.styling.Stroke;
import org.geotools.styling.StyleBuilder;

/**
 * Stroke panel
 * 
 * @author Johann Sorel
 *
 * @source $URL: http://svn.osgeo.org/geotools/tags/2.6.2/modules/unsupported/widgets-swing-pending/src/main/java/org/geotools/gui/swing/style/sld/JStrokePane.java $
 */
public class JStrokePane extends javax.swing.JPanel implements StyleElementEditor<Stroke>{
    
    private MapLayer layer = null;
    private Stroke stroke = null;

    /** 
     * Creates new form JStrokePanel 
     */
    public JStrokePane() {
        super();
        initComponents();
        init();

    }

    private void init() {
        GuiStrokeWidth.setType(JExpressionPane.EXP_TYPE.NUMBER);
        GuiStrokeAlpha.setType(JExpressionPane.EXP_TYPE.OPACITY);
        GuiStrokeColor.setType(JExpressionPane.EXP_TYPE.COLOR);
    }

    public void setLayer(MapLayer layer) {
        this.layer = layer;
        GuiStrokeWidth.setLayer(layer);
        GuiStrokeColor.setLayer(layer);
        GuiStrokeAlpha.setLayer(layer);
        GuiStrokeLineCap.setLayer(layer);
        GuiStrokeLineJoin.setLayer(layer);
    }    
    
    public MapLayer getLayer() {
        return layer;
    }

    public void setEdited(Stroke stroke) {
        
        this.stroke = stroke;
            
        if (stroke != null) {
//            implemented using two buttons
//            stroke.getGraphicFill();
//            stroke.getGraphicStroke();            
            GuiStrokeLineCap.setLineCap(stroke.getLineCap());
            GuiStrokeLineJoin.setLineJoin(stroke.getLineJoin());
            GuiStrokeDashes.setDashes(stroke.getDashArray());
            GuiStrokeDashes.setOffset(stroke.getDashOffset());
            GuiStrokeWidth.setExpression(stroke.getWidth());
            GuiStrokeColor.setExpression(stroke.getColor());
            GuiStrokeAlpha.setExpression(stroke.getOpacity());
        }
        
    }

    public Stroke getEdited() {
        
        if(stroke == null){
            StyleBuilder sb = new StyleBuilder();
            stroke = sb.createStroke(GuiStrokeColor.getExpression(), GuiStrokeWidth.getExpression());
        }

        apply();
        return stroke;
    }

    public void apply(){
        if(stroke != null){
            stroke.setLineCap(GuiStrokeLineCap.getLineCap());
            stroke.setLineJoin(GuiStrokeLineJoin.getLineJoin());
            stroke.setDashArray(GuiStrokeDashes.getDashes());
            stroke.setDashOffset(GuiStrokeDashes.getOffset());
            stroke.setOpacity(GuiStrokeAlpha.getExpression());
            stroke.setWidth(GuiStrokeWidth.getExpression());
            stroke.setColor(GuiStrokeColor.getExpression());
        }
    }
        
    public Component getComponent() {
        return this;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GuiStrokeDashes = new org.geotools.gui.swing.style.sld.JDashPane();
        butFill = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        butStroke = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        GuiStrokeLineCap = new org.geotools.gui.swing.style.sld.JLinecapPane();
        jLabel2 = new javax.swing.JLabel();
        GuiStrokeLineJoin = new org.geotools.gui.swing.style.sld.JLinejoinPane();
        lbl_b_alpha = new javax.swing.JLabel();
        GuiStrokeAlpha = new org.geotools.gui.swing.style.sld.JExpressionPane();
        lbl_b_width = new javax.swing.JLabel();
        GuiStrokeWidth = new org.geotools.gui.swing.style.sld.JExpressionPane();
        lbl_b_color = new javax.swing.JLabel();
        GuiStrokeColor = new org.geotools.gui.swing.style.sld.JExpressionPane();
        lbl_b_alpha1 = new javax.swing.JLabel();

        setOpaque(false);

        GuiStrokeDashes.setOpaque(false);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/geotools/gui/swing/style/sld/Bundle"); // NOI18N
        butFill.setText(bundle.getString("fill")); // NOI18N
        butFill.setPreferredSize(new java.awt.Dimension(68, 22));
        butFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butFillActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText(bundle.getString("graphic")); // NOI18N

        butStroke.setText(bundle.getString("stroke")); // NOI18N
        butStroke.setPreferredSize(new java.awt.Dimension(68, 22));
        butStroke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butStrokeActionPerformed(evt);
            }
        });

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText(bundle.getString("linecap")); // NOI18N

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText(bundle.getString("linejoin")); // NOI18N

        lbl_b_alpha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_b_alpha.setText(bundle.getString("opacity")); // NOI18N

        lbl_b_width.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_b_width.setText(bundle.getString("width")); // NOI18N

        lbl_b_color.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_b_color.setText(bundle.getString("color")); // NOI18N

        lbl_b_alpha1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_b_alpha1.setText(bundle.getString("dashes")); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(GuiStrokeLineCap, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(layout.createSequentialGroup()
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(GuiStrokeLineJoin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(layout.createSequentialGroup()
                .add(lbl_b_width)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(GuiStrokeWidth, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(lbl_b_color)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(GuiStrokeColor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(layout.createSequentialGroup()
                .add(lbl_b_alpha)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(GuiStrokeAlpha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(layout.createSequentialGroup()
                .add(lbl_b_alpha1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(GuiStrokeDashes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(layout.createSequentialGroup()
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(butStroke, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(butFill, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(new java.awt.Component[] {jLabel1, jLabel2, jLabel3, lbl_b_alpha, lbl_b_alpha1, lbl_b_color, lbl_b_width}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.linkSize(new java.awt.Component[] {GuiStrokeLineCap, GuiStrokeLineJoin}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.linkSize(new java.awt.Component[] {GuiStrokeAlpha, GuiStrokeColor, GuiStrokeWidth}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(GuiStrokeLineCap, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(GuiStrokeLineJoin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lbl_b_color, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(GuiStrokeColor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lbl_b_width, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(GuiStrokeWidth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lbl_b_alpha, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(GuiStrokeAlpha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lbl_b_alpha1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(GuiStrokeDashes, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(butStroke, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(butFill, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void butStrokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butStrokeActionPerformed
             
        JGraphicPane pane = new JGraphicPane();
        pane.setLayer(layer);
        
        if(stroke != null){
            pane.setEdited(stroke.getGraphicStroke());
        }
        
        JSimpleDialog dia = new JSimpleDialog(null,true,pane); 
                
        dia.pack();
        dia.setLocationRelativeTo(butStroke);
        dia.setVisible(true);
        
        if(stroke == null){
            stroke =  new StyleBuilder().createStroke() ;
        }
        stroke.setGraphicStroke(pane.getEdited());
        
}//GEN-LAST:event_butStrokeActionPerformed

    private void butFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butFillActionPerformed
        
        JGraphicPane pane = new JGraphicPane();
        pane.setLayer(layer);
        
        if(stroke != null){
            pane.setEdited(stroke.getGraphicFill());
        }
        
        JSimpleDialog dia = new JSimpleDialog(null,true,pane);        
        dia.pack();
        dia.setLocationRelativeTo(butFill);
        dia.setVisible(true);
        
        if(stroke == null){
            stroke =  new StyleBuilder().createStroke() ;
        }
        stroke.setGraphicFill(pane.getEdited());
        
    }//GEN-LAST:event_butFillActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.geotools.gui.swing.style.sld.JExpressionPane GuiStrokeAlpha;
    private org.geotools.gui.swing.style.sld.JExpressionPane GuiStrokeColor;
    private org.geotools.gui.swing.style.sld.JDashPane GuiStrokeDashes;
    private org.geotools.gui.swing.style.sld.JLinecapPane GuiStrokeLineCap;
    private org.geotools.gui.swing.style.sld.JLinejoinPane GuiStrokeLineJoin;
    private org.geotools.gui.swing.style.sld.JExpressionPane GuiStrokeWidth;
    private javax.swing.JButton butFill;
    private javax.swing.JButton butStroke;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_b_alpha;
    private javax.swing.JLabel lbl_b_alpha1;
    private javax.swing.JLabel lbl_b_color;
    private javax.swing.JLabel lbl_b_width;
    // End of variables declaration//GEN-END:variables


}
