/**
 * <copyright>
 * </copyright>
 *
 * $Id: InterpolationMethodsTypeValidator.java 29859 2008-04-09 04:42:44Z jdeolive $
 */
package net.opengis.wcs11.validation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link net.opengis.wcs11.InterpolationMethodsType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InterpolationMethodsTypeValidator {
    boolean validate();

    boolean validateInterpolationMethod(EList value);
    boolean validateDefault(String value);
}
